// <auto-generated />
namespace InventoryService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class usuniecie_Range_z_Item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(usuniecie_Range_z_Item));
        
        string IMigrationMetadata.Id
        {
            get { return "202002111026479_usuniecie_Range_z_Item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
